[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "aerostack2_tutorial"
authors = [{name = "Lucca", email = "luccagandra@poli.ufrj.br"}]
dynamic = ["version", "description"]
